apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: papers-image-updater
  namespace: argo-cd
spec:
  namespace: argo-cd
  applicationRefs:
    - namePattern: "papers"
      commonUpdateSettings:
        updateStrategy: "newest-build"
        allowTags: "regexp:^[0-9a-fA-F]{8,40}$"
      writeBackConfig:
        method: "argo"
      images:
        - alias: "papers-frontend"
          imageName: "ghcr.io/unsw-cse-comp99-3900/h09b-banana-frontend"
          manifestTargets:
            helm:
              name: "image.frontend.repository"
              tag: "image.frontend.tag"
        - alias: "papers-migrations"
          imageName: "ghcr.io/unsw-cse-comp99-3900/h09b-banana-migration-runner"
          manifestTargets:
            helm:
              name: "image.migrations.repository"
              tag: "image.migrations.tag"
        - alias: "papers-worker"
          imageName: "ghcr.io/unsw-cse-comp99-3900/h09b-banana-queue-worker"
          manifestTargets:
            helm:
              name: "image.worker.repository"
              tag: "image.worker.tag"
